# Generated by Django 6.0 on 2025-12-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosco24hs', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
    ]
